# -*- coding: utf-8 -*-
"""job_uploader.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1otYPGOxtZmM7n1tkX_hcVlrsstmCKmF9
"""

# from google.colab import drive

# drive.mount('/content/drive')

import json
import datetime
import os
import sys

file_path = sys.argv[1]

job_title=[]
job_description=[]
job_type=[]
salary=[]
company=[]
location=[]
remote=[]
benefits=[]
applied=[]
response=[]
interview=[]

while True:
  print("Title: ")
  job_title.append(input())
  print("Description: ")
  job_description.append(input())
  print("Job Type:")
  job_type.append(input())
  print("Salary: ")
  salary.append(int(input()))
  print("Company: ")
  company.append(input())
  print("Location: ")
  location.append(input())
  print("Remote 1/0: ")
  remote.append(int(input()))
  print("Benefits 1/0:")
  benefits.append(int(input()))
  print("Applied 1/0: ")
  applied.append(int(input()))
  response.append(0)
  interview.append(0)

  print("Add another job? ")
  if int(input()) == 0:
    break

with open(file_path, 'r+') as file:
    data = json.load(file)
    for i in range(len(job_title)):
      data['job list'].append(
        {
          'job_title' : job_title[i],
          'job_description' : job_description[i],
          'job_type' : job_type[i],
          'salary' : salary[i],
          'company' : company[i],
          'location' : location[i],
          'remote' : remote[i],
          'benefits' : benefits[i],
          'applied' : applied[i],
          'response' : response[i],
          'interview' : interview[i]
      })
    # data.update(jobs_to_append)
    file.seek(0)
    json.dump(data, file, indent = 4)
    print(data)


print("Printed above data as json.")

# with open('/content/drive/MyDrive/job_hunt/job list.txt', 'w') as outfile:
#     json.dump(jobs_to_append, outfile)